### PR TITLE
added support for installing SvarDOS

### PR DESCRIPTION
**Pull request by mateuszviste**

### CODE REVIEW

**Comment by stsp** [comment]
I did some changes to the scripts,
and now (if you also update dosemu2
first), you can run `dosemu-install3rdpartydos`
which will present the menu.
Selecting OpenDOS actually should
now work.
Please make sure that it works
for you (I am a newbie in python,
so I could mess things up), and
if it does - please add your DOS
to the same menu.

**Comment by mateuszviste** [comment]
I have added SvarDOS to the install3rdpartydos script. I am no python expert, but it seems I did not break anything, and the script works for me (it downloads and installs SvarDOS in my DOSEMU directory alright).

**Comment by stsp** [comment]
It boots to the R/O partition
where nothing works. Please
see `dosemu-installopendos`
on where to get the provided
fdconfig.sys.
Also please put your dos to
`install/<dos_name>/drive_c`
the same way `dosemu-installopendos`
does. It can then be booted
with `dosemu -dos <dos_name>`

**Comment by mateuszviste** [comment]
I've reordered the drivers as per your request. EMS driver is loaded high now, saving a hundred or so bytes of conventional memory. You are right that config.sys does not contain anything svardos-specific. For now - but this might change in the future.

> Please squash the commits into 1 and re-push.

I have googled out the words and I understand what you mean, but have no much clue how to achieve that. This will probably require that I set up a git client (I use github via svn only so far). I'll look into that, but it will certainly take me a couple of days to get things working. Will ping here again once it is done.

**Comment by stsp** [comment]
But you don't need to close, you
need to re-push into the same PR.

**Pull request closed without merging**
